services:
  - type: web
    name: mispec
    runtime: python
    pythonVersion: "3.12"
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn mispec.wsgi:application --log-file -"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
