# Generated by Django 5.0.2 on 2024-05-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
    ]
