# Generated by Django 5.0.2 on 2024-05-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20240507_1654'),
    ]

    operations = [
    ]
